In [1]:
import numpy as np

In [21]:
X = np.random.randint(10, size=(10,2))
print(f"Data:\n{X}")

Data:
[[9 5]
 [6 0]
 [8 0]
 [6 7]
 [0 5]
 [8 0]
 [5 1]
 [7 1]
 [9 2]
 [0 6]]


# 1.Neurons

### 1.1 Weights

In a neural network, weights do not exist in isolation. For each layer, all the weights are arranged in a single matrix, conventionally called W. What makes this elegant is the geometric interpretation: each column of this matrix carries the weights of a single neuron in that layer. That is, if the layer has 4 neurons, the matrix has 4 columns, and each column concentrates everything that neuron "knows how to look at" in the input.

The lines, in turn, correspond to the input features. If the input vector has 3 dimensions, each column of W will have 3 elements, one for each feature. When you multiply W by the input vector x, what happens is that each neuron calculates its own inner product with x simultaneously, without any explicit loop. The entire layer processes the batch at once with a single linear algebra operation.

Now when there is a second layer, it does not share the same matrix. It requires a new W2 matrix, with completely different dimensions. The number of W2 lines needs to be equal to the number of neurons in the previous layer, because the output of layer 1 becomes the input of layer 2. The number of columns of W2 defines how many neurons layer 2 has. Each new layer is literally a new linear transformation, represented by a new independent matrix.

This is why stacking layers in a neural network is equivalent to composing linear transformations separated by nonlinearities. Each matrix W learns to project the data into a new space, and the depth of the network is the number of such chained projections.

In [9]:
layer1 = np.random.randn(2, 5) 


""" 
# Rows X columns
# The size of rows (layer1) might be see the same as the INPUT features
# The size of columns (layer1) might be the numbers of neurons for that layer
# The output of each neuron gonna be the input for the next layers, so we call them Z

"""



layer2 = np.random.randn(5, 5)

"""
# Rows X columns
# The size of rows (layer2) might be see the same as the INP features
# THe size of columns (layer2) might be the numbers of neurons for that layer
"""

print(f"Layer 1:\n{layer1}\n")
print(f'Layer 2:\n{layer2}\n')


Layer 1:
[[-0.55556471  0.35383382  1.30260808  0.85031015  1.3154743 ]
 [ 0.86521962 -0.01621829  0.54965978 -0.10790805  1.05853004]]

Layer 2:
[[-0.61532576 -1.95036145  1.3979721  -0.31367441  0.0900765 ]
 [ 0.773814   -0.1573765  -1.55859857  0.11038073 -0.80616068]
 [-0.29249556  0.70303783 -0.3835      1.11216019  1.16595657]
 [ 1.69801775  1.21816709 -2.17325554  0.98911642  0.68061341]
 [ 1.55204189 -0.16705198  0.99921916  0.29550925  0.79003621]]



### 1.1 Neurons

In [25]:
# z1 was the scalar value that was spat from the neuron
z1 = np.dot(X, layer1)

print(f'Z1:\n{z1}')

Z1:
[[-0.67398434  3.10341291 14.47177159  7.11325106 17.13191893]
 [-3.33338828  2.12300292  7.81564845  5.10186089  7.89284583]
 [-4.44451771  2.83067056 10.4208646   6.80248118 10.52379444]
 [ 2.72314904  2.00947486 11.66326693  4.34650451 15.30255609]
 [ 4.32609809 -0.08109147  2.74829891 -0.53954027  5.29265019]
 [-4.44451771  2.83067056 10.4208646   6.80248118 10.52379444]
 [-1.91260395  1.75295081  7.06270016  4.14364268  7.63590156]
 [-3.02373338  2.46061845  9.66791631  5.84426298 10.26685017]
 [-3.26964319  3.15206779 12.82279224  7.43697522 13.95632881]
 [ 5.19131771 -0.09730976  3.29795869 -0.64744832  6.35118022]]
