# Geral `.nn`

Quando você usa nn.Linear, você está criando um objeto. Esse objeto guarda coisas dentro dele (os pesos e o viés).
- Pense assim: É como uma gaveta. Você coloca o nn.Linear no seu modelo e ele guarda os pesos lá dentro. Por isso, quando você pede model.parameters(), o PyTorch sabe onde procurar.
- Ideal para: Quando você precisa que o PyTorch lembre de algo (pesos, bias, estatísticas de uma BatchNorm).

### (1) `nn.Linear()`


Simula os pesos de uma camada inteira. É a implementação de uma Transformação Afim. Ele encapsula a lógica de multiplicação matricial entre o vetor de entrada e uma matriz de pesos treináveis. tem o shape de (input, output), aonde o input representa o total de samples que iremos receber e o output são os números de neurônios       

In [2]:
import torch.nn as nn
import torch

x = torch.rand(2, 2)
layer1 = nn.Linear(2, 5)
z = layer1(x)

print(f'Data input (x):\n{x}\n')
print(f'Weights of the layer: \n{layer1.state_dict()}\n')
print(f'Output x @ layer1.T: \n{z}\n')

Data input (x):
tensor([[0.5253, 0.7415],
        [0.4712, 0.5271]])

Weights of the layer: 
OrderedDict({'weight': tensor([[-0.3516,  0.3899],
        [-0.6501,  0.2773],
        [-0.3923, -0.1118],
        [ 0.4181, -0.0218],
        [-0.4690,  0.3521]]), 'bias': tensor([-0.5689, -0.5518,  0.2935, -0.2464, -0.6520])})

Output x @ layer1.T: 
tensor([[-0.4645, -0.6877,  0.0046, -0.0430, -0.6373],
        [-0.5290, -0.7120,  0.0498, -0.0609, -0.6874]],
       grad_fn=<AddmmBackward0>)



### (2) `nn.Sequential()`

Aqui podemos acumular modulos em uma sequencia, como blocos, agrupa várias camadas em uma sequência fixa. Quando você passa um dado por ele, o dado entra na primeira camada, o resultado vai para a segunda, depois para a terceira, e assim por diante.

In [ ]:
modules_block1 = nn.Sequential(
    nn.Linear(1, 1), # layer 1 block 1
    nn.Linear(1, 1) # layer 1 block 1
)

modules_block1 = nn.Sequential(
    nn.Linear(1, 1), # layer 1 block 2
    nn.Linear(1, 1) # layer 2 block 2
)

### (3) `nn.ModuleList()`

Função utilizada para repetir um bloco, sequencia ou etc

In [5]:
x = torch.rand(2,2)
layers = nn.ModuleList(nn.Linear(2,2) for _ in range(4))

for a, layer in enumerate(layers):
    x = layer(x)
    print(f'Layer: {a}, value:\n{x}')
 

Layer: 0, value:
tensor([[0.7903, 0.5556],
        [0.6992, 0.5534]], grad_fn=<AddmmBackward0>)
Layer: 1, value:
tensor([[-1.3824, -0.0577],
        [-1.3335, -0.0754]], grad_fn=<AddmmBackward0>)
Layer: 2, value:
tensor([[0.8793, 0.6223],
        [0.8516, 0.5911]], grad_fn=<AddmmBackward0>)
Layer: 3, value:
tensor([[-0.3173, -0.6329],
        [-0.3204, -0.6181]], grad_fn=<AddmmBackward0>)
